import { ClinicalRenderer } from './ClinicalRenderer.js';
import { ClinicalTables } from './components/ClinicalTables.js';

export class ClinicalUI {
    constructor(engine) {
        this.engine = engine;
        this.container = null;

        // Bind methods so they can be securely used in event listeners
        this.startSpecificCase = this.startSpecificCase.bind(this);
        this.startBeginnerCases = this.startBeginnerCases.bind(this);
        this.startIntermediateCases = this.startIntermediateCases.bind(this);
        this.startExpertCases = this.startExpertCases.bind(this);
        this.startNewCase = this.startNewCase.bind(this);

        this.showPhysicalExam = this.showPhysicalExam.bind(this);
        this.showDifferentialBuilder = this.showDifferentialBuilder.bind(this);
        this._handleDifferentialSubmit = this._handleDifferentialSubmit.bind(this);
        this.showEMGDecision = this.showEMGDecision.bind(this);
        this.proceedAfterDecision = this.proceedAfterDecision.bind(this);
        this.showFinalDiagnosis = this.showFinalDiagnosis.bind(this);
        this._handleFinalDiagnosisSubmit = this._handleFinalDiagnosisSubmit.bind(this);
    }

    // --- Core API ---

    renderDashboard(pgyLevel) {
        const content = ClinicalRenderer.renderDashboard(pgyLevel, this.engine.database);

        // 1. Candyland Core Integration Check
        const activeCandylandModal = document.querySelector('.learning-modal-overlay.active .learning-modal');

        if (activeCandylandModal) {
            console.log('🏥 Injecting directly into active Candyland module...');
            activeCandylandModal.innerHTML = `
                <div style="padding: 25px; border-bottom: 2px solid #e5e7eb; background: linear-gradient(135deg, #f3f4f6, #e5e7eb); border-radius: 15px 15px 0 0; position: relative;">
                    <h2 style="margin: 0; color: #1f2937; font-size: 24px; font-weight: 700;">🏥 Clinical Cases</h2>
                    <button class="modal-close-btn" onclick="document.querySelector('.learning-modal-overlay.active').remove()" style="position: absolute; top: 20px; right: 20px; background: #ef4444; color: white; border: none; font-size: 20px; cursor: pointer; width: 35px; height: 35px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; transition: all 0.2s;">×</button>
                </div>
                <div id="clinical-root" style="padding: 30px; background: white; border-radius: 0 0 15px 15px; overflow-y: auto; max-height: 80vh;">
                    ${content}
                </div>
            `;
            this.container = document.getElementById('clinical-root');
        } else if (window.showModal) {
            window.showModal('Clinical Cases', `<div id="clinical-root">${content}</div>`);
            this.container = document.getElementById('clinical-root');
        }

        this._attachDashboardListeners();
    }

    _attachDashboardListeners() {
        if (!this.container) return;

        // Attach event listeners to the cards rendered by ClinicalRenderer
        const cards = this.container.querySelectorAll('.difficulty-card');
        cards.forEach(card => {
            const onclickAttr = card.getAttribute('onclick');
            if (onclickAttr && onclickAttr.includes('startSpecificCase')) {
                const caseId = onclickAttr.match(/'([^']+)'/)[1];
                card.onclick = () => this.startSpecificCase(caseId);
            } else if (onclickAttr && onclickAttr.includes('startBeginnerCases')) {
                card.onclick = this.startBeginnerCases;
            } else if (onclickAttr && onclickAttr.includes('startIntermediateCases')) {
                card.onclick = this.startIntermediateCases;
            } else if (onclickAttr && onclickAttr.includes('startExpertCases')) {
                card.onclick = this.startExpertCases;
            }
        });

        // Filter out global returns (returnToPGYNavigator doesn't belong to this class)
        // Note: The global window.returnToPGYNavigator still needs to fire, 
        // so we leave that inline attribute untouched in ClinicalRenderer.
    }

    _attachInterfaceListeners() {
        if (!this.container) return;

        // Wire up all buttons generated by ClinicalRenderer.renderInterfaceShell

        // View buttons
        const btnPhysicalExam = this.container.querySelector('button[onclick*="showPhysicalExam"]');
        if (btnPhysicalExam) btnPhysicalExam.onclick = this.showPhysicalExam;

        const btnDifferential = this.container.querySelector('button[onclick*="showDifferentialBuilder"]');
        if (btnDifferential) btnDifferential.onclick = this.showDifferentialBuilder;

        const btnAnalyzeDiff = this.container.querySelector('button[onclick*="analyzeDifferential"]');
        if (btnAnalyzeDiff) btnAnalyzeDiff.onclick = this._handleDifferentialSubmit;

        const btnEMGDecision = this.container.querySelector('button[onclick*="showEMGDecision"]');
        if (btnEMGDecision) btnEMGDecision.onclick = this.showEMGDecision;

        const btnProceedDecision = this.container.querySelector('button[onclick*="proceedAfterDecision"]');
        if (btnProceedDecision) btnProceedDecision.onclick = this.proceedAfterDecision;

        const btnFinalForm = this.container.querySelector('button[onclick*="showFinalDiagnosis"]');
        if (btnFinalForm) btnFinalForm.onclick = this.showFinalDiagnosis;

        const btnSubmitDiag = this.container.querySelector('button[onclick*="checkFinalDiagnosis"]');
        if (btnSubmitDiag) btnSubmitDiag.onclick = this._handleFinalDiagnosisSubmit;

        const btnQuitList = this.container.querySelectorAll('button[onclick*="startNewCase"]');
        btnQuitList.forEach(btn => btn.onclick = this.startNewCase);

        // EMG Decision cards
        const emgIndicatedCard = this.container.querySelector('div[onclick*="makeEMGDecision(true)"]');
        if (emgIndicatedCard) emgIndicatedCard.onclick = () => this._handleEMGDecisionClick(true);

        const emgNotIndicatedCard = this.container.querySelector('div[onclick*="makeEMGDecision(false)"]');
        if (emgNotIndicatedCard) emgNotIndicatedCard.onclick = () => this._handleEMGDecisionClick(false);
    }

    // --- Interaction Routing ---

    startSpecificCase(caseId) {
        try {
            const caseData = this.engine.loadCase(caseId);

            // UI Transitions
            const selDiv = document.getElementById('case-selection');
            if (selDiv) selDiv.style.display = 'none';
            const intDiv = document.getElementById('case-interface');
            if (intDiv) intDiv.style.display = 'block';

            this._attachInterfaceListeners();
            this._populateCaseDetails(caseData);
            this._transitionToStep('case-presentation-step', 20);

        } catch (e) {
            console.error(e);
            alert('Case not available.');
        }
    }

    startNewCase() {
        this.engine.currentCase = null;

        // Just re-render the dashboard to reset state
        const selDiv = document.getElementById('case-selection');
        const intDiv = document.getElementById('case-interface');

        if (selDiv && intDiv) {
            intDiv.style.display = 'none';
            selDiv.style.display = 'block';

            // Hide all steps
            const steps = ['case-presentation-step', 'physical-exam-step', 'differential-step', 'emg-decision-step', 'results-step', 'diagnosis-step'];
            steps.forEach(id => {
                const el = document.getElementById(id);
                if (el) el.style.display = 'none';
            });

            this._updateProgress(0);
        } else {
            // Fallback: full re-render
            this.renderDashboard('all');
        }
    }

    // Stubbed category loaders
    startBeginnerCases() { alert('Category filter not yet implemented. Please select a specific case.'); }
    startIntermediateCases() { alert('Category filter not yet implemented. Please select a specific case.'); }
    startExpertCases() { alert('Category filter not yet implemented. Please select a specific case.'); }

    // --- State & Stepping Handlers ---

    _transitionToStep(stepId, percentage) {
        const steps = ['case-selection', 'case-presentation-step', 'physical-exam-step', 'differential-step', 'emg-decision-step', 'results-step', 'diagnosis-step'];

        steps.forEach(id => {
            const el = document.getElementById(id);
            if (el) {
                if (id === stepId) {
                    el.classList.add('active-step');
                    el.style.display = 'block';
                    // Trigger reflow for animation
                    void el.offsetWidth;
                    el.style.opacity = '1';
                    el.style.transform = 'translateY(0)';
                } else {
                    el.classList.remove('active-step');
                    el.style.opacity = '0';
                    el.style.transform = 'translateY(10px)';
                    // Delay hiding to allow transition
                    setTimeout(() => {
                        if (!el.classList.contains('active-step')) {
                            el.style.display = 'none';
                        }
                    }, 400);
                }
            }
        });

        if (percentage !== undefined) {
            this._updateProgress(percentage);
        }
    }

    _populateCaseDetails(caseData) {
        const detailsDiv = document.getElementById('case-details');
        if (detailsDiv) detailsDiv.innerHTML = ClinicalRenderer.renderCaseDetails(caseData);

        const examDiv = document.getElementById('physical-exam-details');
        if (examDiv) examDiv.innerHTML = ClinicalRenderer.renderPhysicalExam(caseData.physicalExam);
    }

    _updateProgress(percentage) {
        const bar = document.getElementById('progress-fill');
        if (bar) bar.style.width = percentage + '%';
    }

    showPhysicalExam() { this._transitionToStep('physical-exam-step', 40); }
    showDifferentialBuilder() { this._transitionToStep('differential-step', 60); }
    showEMGDecision() { this._transitionToStep('emg-decision-step', 70); }
    showFinalDiagnosis() { this._transitionToStep('diagnosis-step', 90); }

    proceedAfterDecision() {
        this._transitionToStep('results-step', 80);

        const caseData = this.engine.currentCase;
        const ncsDiv = document.getElementById('ncs-results');
        if (ncsDiv) ncsDiv.innerHTML = ClinicalTables.generateNCSTable(caseData);

        const emgTitle = document.getElementById('emg-results');
        const emgDetailDiv = document.getElementById('emg-details');

        if (emgTitle && emgDetailDiv) {
            if (caseData.emgStudies) {
                emgTitle.style.display = 'block';
                emgDetailDiv.innerHTML = ClinicalTables.generateEMGTable(caseData.emgStudies);
            } else {
                emgTitle.style.display = 'none';
                emgDetailDiv.innerHTML = '';
            }
        }
    }

    // --- Input & Evaluation Handlers ---

    _handleDifferentialSubmit() {
        const inputEl = document.getElementById('user-differential');
        if (!inputEl) return;

        const results = this.engine.analyzeDifferential(inputEl.value);

        const feedbackDiv = document.getElementById('differential-feedback');
        if (feedbackDiv) {
            // Note: The original ClinicalRenderer.renderDifferentialFeedback takes (results, expectedDifferentials)
            // It only structurally needs results.matched, results.totalExpected.
            feedbackDiv.innerHTML = ClinicalRenderer.renderDifferentialFeedback(results, results.expectedData);
            feedbackDiv.style.display = 'block';
        }

        const nextBtn = document.getElementById('continue-to-studies');
        if (nextBtn) nextBtn.style.display = 'inline-block';
    }

    _handleEMGDecisionClick(isIndicated) {
        const evaluation = this.engine.evaluateEMGDecision(isIndicated);

        const feedbackDiv = document.getElementById('emg-decision-feedback');
        if (feedbackDiv) {
            feedbackDiv.innerHTML = ClinicalRenderer.renderEMGDecisionFeedback(evaluation);
            feedbackDiv.style.display = 'block';
        }

        const continueBtn = document.getElementById('continue-after-decision');
        if (continueBtn) {
            continueBtn.style.display = 'inline-block';
        }
    }

    _handleFinalDiagnosisSubmit() {
        const inputEl = document.getElementById('final-diagnosis');
        if (!inputEl) return;

        // Ask engine if correct
        const isCorrect = this.engine.evaluateFinalDiagnosis(inputEl.value);

        // Tell renderer to show answers
        const feedbackDiv = document.getElementById('diagnosis-feedback');
        if (feedbackDiv) {
            feedbackDiv.innerHTML = ClinicalRenderer.renderFinalDiagnosis(isCorrect, this.engine.currentCase, inputEl.value);
            feedbackDiv.style.display = 'block';
        }

        this._updateProgress(100);
    }
}
